name: Free Windows RDP via Tailscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      
      - name: Download and Install Tailscale
        shell: powershell
        run: |
          $ProgressPreference = 'SilentlyContinue'
          echo "Downloading Tailscale..."
          
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.msi" -OutFile "tailscale.msi"
          echo "Installing Tailscale..."
          Start-Process msiexec.exe -ArgumentList '/i tailscale.msi /qn /norestart' -Wait
          echo "Tailscale installed successfully!"

      
      - name: Connect to Tailscale Network
        shell: powershell
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=$env:TAILSCALE_AUTH_KEY --accept-routes

      
      - name: Enable RDP and Setup User
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
          $Password = ConvertTo-SecureString "GitHubRDP@2026" -AsPlainText -Force
          Set-LocalUser -Name "runneradmin" -Password $Password

      
      - name: Keep Alive Loop
        shell: powershell
        run: |
          $hours = 6
          for ($i = 0; $i -lt ($hours * 60); $i++) {
              Start-Sleep -Seconds 60
          }
